name = "ToyRegistry"
repo = "git@github.com:jw3126/ToyRegistry.git"
uuid = "071889fc-69e7-11e9-1128-41fb1ef377da"

[packages]
6bad61c4-3c25-5a46-b15a-41e8b48bfd73 = { name = "ToyPkg", path = "T/ToyPkg" }
